# PostgreSQL configuration
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: fantasy_baseball_draft_compare_development

test:
  <<: *default
  database: fantasy_baseball_draft_compare_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
